# .github/workflows/docker-build.yml
name: CI/CD Pipeline # 工作流名称

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

on: # 触发条件
  push:
    branches: ["main"] # main分支提交时触发
  pull_request:
    branches: ["main"]

jobs: # 定义任务
  build-and-test: # 任务ID
    runs-on: ubuntu-latest # 运行环境
    steps:
      # 步骤1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2：登录容器注册中心
      - name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 步骤3：设置构建元数据
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      # 步骤4：构建并推送镜像（支持缓存）
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # 指定Dockerfile路径
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 步骤5：触发外部部署（如Portainer）
      - name: Trigger Portainer Webhook
        if: success()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.PORTAINER_WEBHOOK_URL }}?trigger_force_update=true"
